// Product catalog for the static Bella Wigs site.
// Images reference files in assets/images/new-arrivals/

const BADGE_LABELS = {
  "best-seller": "Best Seller",
  "new": "New",
  "limited": "Limited",
  "low-stock": "Low Stock"
};

const PRODUCTS = [

  // =========================
  // EXISTING PRODUCTS
  // =========================

  {
    id: "1",
    name: "13x4 Lace Front Wig, 22\"",
    category: "Straight Wigs",
    hair_type: "Brazilian Remy",
    density: "180%",
    lace: "13x4 Lace Front",
    length: 22,
price: 12500,
    image: "13x4-lace-front.png",
    badge: "best-seller"
  },

  {
    id: "2",
    name: "Glueless 13x4 HD Lace Front Wig",
    category: "Straight Wigs",
    hair_type: "100% Human Hair",
    density: "150%",
    lace: "13x4 HD Lace",
    length: 20,
price: 11500,
    image: "glueless-13x4-hd.png",
    badge: null
  },

  {
    id: "3",
    name: "Chic Bob Wig, Closure Fringe",
    category: "Bob Wigs",
    hair_type: "100% Human Hair",
    density: "150%",
    lace: "Closure",
    length: 12,
price: 7500,
    image: "sdd_closure_fringe_bob_wig-1.png",
    badge: null
  },

  {
    id: "4",
    name: "Sleek Pixie Cut Wig",
    category: "Pixie Wigs",
    hair_type: "100% Human Hair",
    density: "130%",
    lace: "Fringe, No Lace",
    length: 8,
price: 7500,
    image: "hair_type___classy_boss_pixie_.png",
    badge: null
  },

  {
    id: "5",
    name: "Peruvian Water Wave 20\"",
    category: "Water Wave Wigs",
    hair_type: "100% Human Hair",
    density: "180%",
    lace: "5x5 Closure, HD Lace",
    length: 20,
price: 12500,
    image: "water-wave-wig.png",
    badge: "best-seller"
  },

  {
    id: "6",
    name: "Balayage Body Wave Wig",
    category: "Water Wave Wigs",
    hair_type: "100% Human Hair",
    density: "150%",
    lace: "Lace Front",
    length: 18,
price: 11500,
    image: "deep-wave-human.png",
    badge: null
  },

  {
    id: "7",
    name: "Wavy Curls Wig",
    category: "Water Wave Wigs",
    hair_type: "100% Human Hair",
    density: "150%",
    lace: "Closure",
    length: 20,
price: 11500,
    image: "wavy-curls-wig.png",
    badge: null
  },

  {
    id: "8",
    name: "Kinky Afro Curl Wig 16\"",
    category: "Afro Wigs",
    hair_type: "LDYESTIM Human Hair",
    density: "180%",
    lace: "Full Lace",
    length: 16,
price: 10500,
    image: "ldyestim_kinky_curly_lace_fron.png",
    badge: "new"
  },

  // =========================
  // NEW ARRIVALS
  // =========================

  {
    id: "9",
    name: "Sleek Jet Black Bob Wig",
    category: "Bob Wigs",
    hair_type: "100% Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 12,
price: 12000,
    image: "new-arrivals/_sleek_jet_black_bob_wig__ever.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "10",
    name: "Sleek Jet Black Lace Front Bob",
    category: "Bob Wigs",
    hair_type: "100% Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 12,
price: 11000,
    image: "new-arrivals/Sleek Jet Black Bob Wig Everyday Chic Lace Front (1).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "11",
    name: "13x4 HD Body Wave Lace Front",
    category: "Body Wave Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "13x4 HD Lace",
    length: 24,
price: 16500,
    image: "new-arrivals/13x4 HD Lace Front Wigs Human Hair 180 Density Body Wave Lace Front Wigs Human Hair Pre Plucked Frontal Wigs Human Hair Lace Wig For Women Body Wave Wig With Baby Hair Natural Black 40 Inch.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "12",
    name: "16\" SDD 5x5 Bounce Unit",
    category: "Body Wave Wigs",
    hair_type: "Super Double Drawn Human Hair",
    density: "200%",
    lace: "5x5 Closure",
    length: 16,
price: 14000,
    image: "new-arrivals/SDD 5x5 Bounce Unit Soft full silky.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "13",
    name: "22\" SDD Wavy Bounce Unit",
    category: "Water Wave Wigs",
    hair_type: "Virgin Human Hair",
    density: "200%",
    lace: "5x5 Closure",
    length: 22,
price: 14000,
    image: "new-arrivals/5x5 Wavy Weave Virgin Hair SDD Bouncy Curls.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "14",
    name: "30\" Honey Blonde HD Lace Wig",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "250%",
    lace: "13x6 HD Lace",
    length: 30,
price: 16000,
    image: "new-arrivals/30 inch honey blonde 13x6 hd lace frontal wig prepluck 13x4 blonde straight lace front wig human hair.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "15",
    name: "30\" Wavy Human Hair Wig",
    category: "Water Wave Wigs",
    hair_type: "100% Human Hair",
    density: "200%",
    lace: "Lace Front",
    length: 30,
price: 14000,
    image: "new-arrivals/30inches wavy hair.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "16",
    name: "Ash Blonde Luxury Wig",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 20,
price: 18500,
    image: "new-arrivals/Ash Blond wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "17",
    name: "Brazilian Curly Wave Wig",
    category: "Curly Wigs",
    hair_type: "Brazilian Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 20,
price: 17500,
    image: "brazilian_curly_wave_wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "18",
    name: "Ginger Orange Body Wave Wig",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "13x4 Transparent Lace",
    length: 24,
price: 18000,
    image: "new-arrivals/Ginger Orange Body Wave 13x4 Transparent Lace Front Wig Human Hair for Women 350 Colored Pre.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "19",
    name: "Honey Blonde Layered Lace Front",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 22,
price: 18000,
    image: "new-arrivals/Honey Blonde Layered Lace Front Wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "20",
    name: "HD Real Scalp Curtain Bangs Wig",
    category: "Body Wave Wigs",
    hair_type: "Human Hair",
    density: "150%",
    lace: "13x4 HD Lace",
    length: 24,
price: 17000,
    image: "new-arrivals/Klaiyi Hair HD Real Scalp Wig with Curtain Bangs 13x4 Invisible Lace Frontal Body Wave Wig Natural Black Color.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "21",
    name: "30\" Water Wave Lace Frontal",
    category: "Water Wave Wigs",
    hair_type: "Human Hair",
    density: "220%",
    lace: "Transparent Lace Frontal",
    length: 30,
price: 14000,
    image: "new-arrivals/Lilluxe Hair Water Wave Human Hair 30 Inches Transparent Lace Frontal 220 Density Black.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "22",
    name: "Honey Brown Wavy Highlight Wig",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 22,
price: 17500,
    image: "new-arrivals/Long Side Part Wavy Rich Honey Brown with Blonde Highlights Lace Front Wigs.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "23",
    name: "613 Closure Wig",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "613 Closure",
    length: 20,
price: 17000,
    image: "new-arrivals/Natural Part Perfection with a 613 Closure Wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "24",
    name: "P427 Highlight Body Wave Wig",
    category: "Body Wave Wigs",
    hair_type: "Brazilian Virgin Human Hair",
    density: "180%",
    lace: "13x4 HD Lace",
    length: 24,
price: 18500,
    image: "new-arrivals/P427 Highlight Body Wave Human Hair Wig Pre Plucked Baby Hair 13x4 HD Transparent Lace Front Wig 180 Density Brazilian Virgin Hair Wig For Women.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "25",
    name: "30\" HD Lace Front Human Hair Wig",
    category: "Straight Wigs",
    hair_type: "100% Human Hair",
    density: "250%",
    lace: "13x6 HD Lace",
    length: 30,
price: 12000,
    image: "new-arrivals/Perruque Lace Front Wig 100 naturelle cheveux bruts haute densite 250 13x6 HD 30 40 pouces 5x5 sans colle 13x6.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "26",
    name: "Short Curly Pixie Wig",
    category: "Pixie Wigs",
    hair_type: "Human Hair",
    density: "150%",
    lace: "Fringe",
    length: 8,
price: 8500,
    image: "new-arrivals/Short Curly Pixie Cut Wigs For Black Women Synthetic Afro Pixie Wig Synthetic Heat Resistant Full Wigs Black Color Short Curly Pixie Wigs For Women.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "27",
    name: "P4/27 Honey Blonde Highlight Wig",
    category: "Colored Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "13x6 HD Lace",
    length: 24,
price: 18500,
    image: "new-arrivals/Smilegirl P4_27 Honey Blonde Body Wave Highlight Human Hair Wig 13x6 HD Lace Frontal Wig Pre-plucked.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "28",
    name: "Classic Wavy Human Hair Wig",
    category: "Water Wave Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 20,
price: 14000,
    image: "new-arrivals/Wavy.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "29",
    name: "180% Water Wave 5x5 Unit",
    category: "Water Wave Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "5x5 Closure",
    length: 20,
price: 14000,
    image: "new-arrivals/180_density___water_wave_5x5_c.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "30",
    name: "Water Wave Human Hair Wig",
    category: "Water Wave Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "Lace Front",
    length: 20,
price: 14000,
    image: "water_wave_wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

  {
    id: "31",
    name: "Pre-Plucked 360 Lace Wig",
    category: "Lace Front Wigs",
    hair_type: "Human Hair",
    density: "180%",
    lace: "360 Lace",
    length: 20,
price: 15500,
    image: "new-arrivals/pre-plucked-360.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },

{
    id: "32",
    name: "Arlalgce Bob Wig",
    category: "Bob Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 8500,
    image: "new-arrivals/arlalgce-bob-wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "33",
    name: "Bob Wig Human",
    category: "Bob Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 8500,
    image: "new-arrivals/bob-wig-human.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "34",
    name: "Chocolate Brown Deep Wave Bob Wig",
    category: "Bob Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 8500,
    image: "new-arrivals/chocolate-brown-deep-wave-bob-wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "35",
    name: "Sdd Closure Fringe Bob Wig Ftl",
    category: "Bob Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 7500,
    image: "new-arrivals/sdd_closure_fringe_bob_wig_ftl.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "36",
    name: "Chocolate Brown Layered",
    category: "Colored Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12000,
    image: "new-arrivals/chocolate-brown-layered.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "37",
    name: "Honey Blonde Brown Highlight Body Wave",
    category: "Colored Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 9500,
    image: "new-arrivals/Klaiyi Body Wave Honey Blonde Brown Bundles Highlight Human Hair Wave Extensions 16 18 18.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "38",
    name: "Ultra Hold Lace Wig Glue",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 2500,
    image: "new-arrivals/150ml Ultra Hold Front Lace Wig Glue Waterproof Strong Bond Hair Adhesive for Lace Wig Hair.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "39",
    name: "Anua Products",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 4500,
    image: "new-arrivals/Anua products.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "40",
    name: "Centella Glow Skincare Set",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/Centella Skincare Routine Korean Skincare Products for Glowing Healthy Skin.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "41",
    name: "CeraVe SPF 50 Mineral Sunscreen",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3000,
    image: "new-arrivals/CeraVe Hydrating Mineral Sunscreen SPF 50 Review Best Body Sunscreen for Dry Sensitive Skin.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "42",
    name: "CeraVe Hydrating Skincare",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/Cerave products is your go to for soft smooth.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "43",
    name: "Charcoal Mask",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 1500,
    image: "new-arrivals/Charcoal Mask.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "44",
    name: "COSRX Snail Mucin Moisture Cream",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 4500,
    image: "new-arrivals/COSRX Moisture Booster Snail Mucin 92 Moisturizer 6X Peptide Collagen Booster Toner Serum.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "45",
    name: "COSRX 6 Peptide Skin Booster",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/COSRX The 6 Peptide Skin Booster Serum 150ml 6 Peptide Complex Brightening Face Serum Multiple Skin.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "46",
    name: "COSRX 6 Peptide Serum",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/CosRX The 6 Peptide Skin Booster Serum Now Available Musings of a Muse.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "47",
    name: "Dan Technology Flat Iron And Small Hot Comb For Black Women's Hair, Wigs Hair Stra (1)",
    category: "Accessories",
    keywords: ["wig tools","wig maintenance kit","wig care","hair tools","flat iron","hot comb","straightener","styling tool","wig styling"],
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DAN Technology Flat Iron and Small Hot Comb for Black Womens Hair Wigs Hair Stra (1).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "48",
    name: "Dolahair Lace Melting Spray",
    category: "Accessories",
    keywords: ["wig maintenance kit","wig care","lace care","lace adhesive","wig glue","glue","adhesive","lace melting","melting spray","holding spray","wig installation","wig installation kit"],
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 2500,
    image: "new-arrivals/Dolahair Lace Melting and Holding Spray Glue Less Hair Adhesive for Wigs Lace Bond Adhes.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "49",
    name: "Dr Rashel",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR RASHEL.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "50",
    name: "Dr Rashel Skin, Hair & Body Care Products Trusted Skincare Brand (1)",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR_Rashel Skin Hair Body Care Products Trusted Skincare Brand (1).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "51",
    name: "Dr Rashel Skin, Hair & Body Care Products Trusted Skincare Brand (2)",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR_Rashel Skin Hair Body Care Products Trusted Skincare Brand (2).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "52",
    name: "Dr Rashel Skin, Hair & Body Care Products Trusted Skincare Brand (3)",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR_Rashel Skin Hair Body Care Products Trusted Skincare Brand (3).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "53",
    name: "Dr Rashel Skin, Hair & Body Care Products Trusted Skincare Brand (4)",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR_Rashel Skin Hair Body Care Products Trusted Skincare Brand (4).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "54",
    name: "Dr Rashel Skin, Hair & Body Care Products Trusted Skincare Brand (5)",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR_Rashel Skin Hair Body Care Products Trusted Skincare Brand (5).png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "55",
    name: "Dr Rashel Skin, Hair & Body Care Products Trusted Skincare Brand",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/DR_Rashel Skin Hair Body Care Products Trusted Skincare Brand.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "56",
    name: "Dr Rashel",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/Dr_Rashel.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "57",
    name: "Jade Roller & Gua Sha Set",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 2000,
    image: "new-arrivals/Glow naturally with our Jade Roller Gua Sha.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "58",
    name: "Medicube Pink Pdrn Serum Korean Skincare",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 4500,
    image: "new-arrivals/medicube pink pdrn serum Korean skincare.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "59",
    name: "Orynne 3-10'' Small Flat Irons For Short Hair Pixie Cut",
    category: "Accessories",
    keywords: ["wig tools","wig maintenance kit","wig care","hair tools","flat iron","straightener","styling tool","hot tool","short hair","pixie hair"],
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 2500,
    image: "new-arrivals/ORYNNE 3-10 Small Flat Irons for Short Hair Pixie Cut.jfif",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "60",
    name: "Professional Skincare Essentials",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 2500,
    image: "new-arrivals/Professional Skincare Routine Glow Up Tips 2026.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "61",
    name: "Skin1004",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/SKIN1004.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "62",
    name: "Sunscreen",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3000,
    image: "new-arrivals/sunscreen.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "63",
    name: "Advanced Skincare Essentials",
    category: "Cosmetic Products",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/These Skincare Products Are the Next Best Thing To Injectables According To a Professional.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "64",
    name: "Professional Hair Styling Flat Iron",
    category: "Accessories",
    keywords: ["wig tools","wig maintenance kit","wig care","flat iron","straightener","hair straightener","styling tools","hair tools"],
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 3500,
    image: "new-arrivals/Best Flat Irons for African American Women Smooth Sleek Hair Fast.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "65",
    name: "Beamach Golden Lure Hair Oil",
    category: "Hair Care",
    keywords: ["hair care","hair oil","wig care","wig maintenance","hair treatment","oil","hair products","hair maintenance","moisturizing"],
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 1500,
    image: "new-arrivals/hair-care-oil.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "66",
    name: "All Curly Style",
    category: "Curly Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12000,
    image: "all-curly-style.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "67",
    name: "Curls Style",
    category: "Curly Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12000,
    image: "new-arrivals/curls_style.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "68",
    name: "Ldyestim Kinky Curly",
    category: "Curly Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 10500,
    image: "new-arrivals/ldyestim-kinky-curly.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "69",
    name: "13X4 Lace Front 1",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12500,
    image: "new-arrivals/13x4-lace-front-1.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "70",
    name: "13X4 Lace Front 2",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12500,
    image: "new-arrivals/13x4-lace-front-2.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "71",
    name: "13X4 Lace Front Human Hair Wig 1",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 13000,
    image: "new-arrivals/13x4_lace_front_human_hair_wig-1.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "72",
    name: "13X4 Lace Front Human Hair Wig",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 13000,
    image: "13x4_lace_front_human_hair_wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "73",
    name: "30\" Ombre Honey Blonde HD Lace Wig",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 25000,
    image: "new-arrivals/30 Inch 250 Density Ombre Honey Blonde Lace Front Wig Human Hair 13x4 HD Highlight Body Wave Lace Front Wigs Human Hair For Women Glueless Pre Plucked With Baby Hair Colored HD Lace Wig Human.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "74",
    name: "Perruque Frontale En",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12000,
    image: "new-arrivals/perruque-frontale-en.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "75",
    name: "Viral HD Lace Frontal Wig",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 10000,
    image: "new-arrivals/Viral Lace Frontal Hairstyles For Women Stunning Hairstyles for a Flawless Natural Look.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "76",
    name: "Jet Black HD Body Wave Lace Front Wig",
    category: "Lace Front Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 14000,
    image: "new-arrivals/Jet Black Body Wave Lace Front Wig HD Pre Plucked Glueless.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "77",
    name: "Burgundy Glueless Lace Front Wig",
    category: "Straight Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 14000,
    image: "new-arrivals/Burgundy Straight Lace Front Wig Glueless Pre Plucked Human Hair Wig.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
  {
    id: "78",
    name: "Sleek Jet Black",
    category: "Straight Wigs",
    hair_type: "",
    density: "",
    lace: "",
    length: 0,
price: 12000,
    image: "new-arrivals/sleek-jet-black.png",
    imagePath: "assets/images/new-arrivals/",
    badge: "new"
  },
];

const OCCASION_MAP = {
  "Office": "Straight Wigs",
  "Wedding": "Water Wave Wigs",
  "Everyday": "Bob Wigs",
  "Church": "Pixie Wigs",
  "Fashion": "Afro Wigs",
  "Cancer Treatment": "all"
};

